/**
 * BMI UMS — Transcript Registry Routes
 *
 * Transcripts MUST be registered server-side so that QR-code verification
 * works on ANY device, not just the browser that issued the document.
 *
 * Security model mirrors the certificate route:
 *   Layer 1 — serial in DB          → proves the transcript was officially issued
 *   Layer 2 — HMAC nonce token in QR → proves the QR was generated by BMI servers
 *   (No offline JWT — transcripts change; a 50-year immutable claim is inappropriate)
 */

import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";
import { randomBytes } from "crypto";
import { rateLimiter } from "hono-rate-limiter";
import { getPocketBase } from "../services/pocketbase.js";
import {
  authMiddleware,
  requireRole,
} from "../middleware/auth.js";
import { logger } from "../utils/logger.js";
import {
  generateIssuanceNonce,
  generateHiddenToken,
  verifyHiddenToken,
  buildVerificationUrl,
} from "../services/certificateSigning.js";
import { errorMessage } from "../utils/helpers.js";
import type { ApiResponse } from "../types/index.js";

const transcriptsRouter = new Hono();

// ─── Rate limiter for public verify endpoint ──────────────────────────────────
const verifyRateLimiter = rateLimiter({
  windowMs: 15 * 60 * 1000, // 15 minutes
  limit: 30,
  standardHeaders: true,
  keyGenerator: (c) =>
    c.req.header("x-forwarded-for") ||
    c.req.header("x-real-ip") ||
    "unknown",
  message: {
    valid: false,
    error: "Too many verification attempts. Please wait 15 minutes.",
    code: "RATE_LIMITED",
  },
});

// ─── Validation schemas ───────────────────────────────────────────────────────
const registerSchema = z.object({
  /** PocketBase student record ID */
  studentId: z.string().min(1),
  studentName: z.string().min(1).max(200),
  programme: z.string().min(1).max(200),
  academicYear: z.string().max(20).optional(),
  /**
   * SHA-256 hex of the academic record payload (grades + GPA).
   * Computed by the frontend at generation time and submitted here.
   * Lets us detect whether academic data changed after issuance.
   */
  contentHash: z.string().length(64).regex(/^[0-9a-f]+$/i),
});

// ─── Helpers ──────────────────────────────────────────────────────────────────
async function logVerification(
  serial: string,
  result: "valid" | "invalid" | "revoked" | "tampered" | "not_found",
  ip: string,
): Promise<void> {
  try {
    const pb = getPocketBase();
    await pb.collection("transcript_verification_logs").create({
      transcript_serial: serial,
      result,
      ip_address: ip,
      timestamp: new Date().toISOString(),
    });
  } catch {
    // Non-critical — never fail verification because logging failed
  }
}

// ─── POST /api/v1/transcripts/register ───────────────────────────────────────
/**
 * Register a transcript in the database and return the HMAC token that must
 * be embedded in the QR code.  Auth-gated (registrar / admin only).
 *
 * Idempotent: if the student already has an ISSUED transcript, returns the
 * existing registration instead of creating a duplicate.
 */
transcriptsRouter.post(
  "/register",
  authMiddleware,
  requireRole("admin", "registrar", "staff"),
  zValidator("json", registerSchema),
  async (c) => {
    try {
      const data = c.req.valid("json");
      const pb = getPocketBase();
      const safe = (v: string) => v.replace(/["'\\]/g, "");

      // ── Idempotency: return existing registration ──────────────────────────
      let existing;
      try {
        existing = await pb.collection("transcripts").getFirstListItem(
          `student_id = "${safe(data.studentId)}" && status = "ISSUED"`,
        );
      } catch {
        existing = null;
      }

      if (existing) {
        const verificationUrl = buildVerificationUrl(
          existing.serial_number,
          existing.hidden_token,
        );
        logger.info("Transcript re-registration (idempotent)", {
          serial: existing.serial_number,
          studentId: data.studentId,
        });
        return c.json<ApiResponse<object>>({
          success: true,
          data: {
            serialNumber: existing.serial_number,
            issuedAt: existing.issued_at,
            verificationUrl,
            // hiddenToken returned again — frontend must re-embed in QR
            hiddenToken: existing.hidden_token,
            reissued: false,
          },
          message: "Existing transcript registration found",
        });
      }

      // ── Generate secure identifiers ────────────────────────────────────────
      const year = new Date().getFullYear();
      const suffix =
        (parseInt(randomBytes(3).toString("hex"), 16) % 900000) + 100000;
      const serialNumber = `BMI-TRANS-${year}-${suffix}`;

      const issuanceNonce = generateIssuanceNonce(); // secret — stored only in DB
      const issueDate = new Date().toISOString().split("T")[0];
      const hiddenToken = generateHiddenToken({
        serial: serialNumber,
        studentId: data.studentId,
        issueDate,
        nonce: issuanceNonce,
      });

      // ── Persist ────────────────────────────────────────────────────────────
      const record = await pb.collection("transcripts").create({
        serial_number: serialNumber,
        student_id: data.studentId,
        student_name: data.studentName,
        programme: data.programme,
        academic_year: data.academicYear ?? `${year}-${year + 1}`,
        content_hash: data.contentHash,
        hidden_token: hiddenToken, // NEVER returned in verify responses
        issuance_nonce: issuanceNonce, // NEVER returned anywhere
        issued_at: new Date().toISOString(),
        status: "ISSUED",
        verification_count: 0,
      });

      const verificationUrl = buildVerificationUrl(serialNumber, hiddenToken);

      logger.info("Transcript registered", {
        serial: serialNumber,
        studentId: data.studentId,
      });

      return c.json<ApiResponse<object>>(
        {
          success: true,
          data: {
            serialNumber,
            issuedAt: record.issued_at,
            verificationUrl,
            /**
             * hiddenToken is returned ONCE here so the frontend can embed it
             * in the QR code.  It is NEVER stored anywhere client-side and
             * NEVER printed on the physical document.
             */
            hiddenToken,
            reissued: true,
          },
        },
        201,
      );
    } catch (error: unknown) {
      logger.error("Transcript registration error:", errorMessage(error));
      return c.json<ApiResponse<never>>(
        { success: false, error: "Failed to register transcript" },
        500,
      );
    }
  },
);

// ─── POST /api/v1/transcripts/verify ─────────────────────────────────────────
/**
 * Public endpoint — verifies a transcript by serial number + HMAC token.
 * Rate limited to 30 requests per 15 minutes per IP.
 *
 * Body: { serial: string, t?: string }
 *   serial — the serial number printed on the document
 *   t      — the HMAC token from the QR code URL (optional; serial-only
 *             verification is allowed but marked as lower confidence)
 */
transcriptsRouter.post("/verify", verifyRateLimiter, async (c) => {
  const ip =
    c.req.header("x-forwarded-for") ||
    c.req.header("x-real-ip") ||
    "unknown";

  try {
    const body = await c.req.json();
    const { serial, t: token } = body as { serial?: string; t?: string };

    // ── Input validation ───────────────────────────────────────────────────
    if (!serial || typeof serial !== "string") {
      return c.json({
        valid: false,
        error: "Serial number is required",
        code: "MISSING_SERIAL",
      });
    }

    const SERIAL_RE = /^BMI-TRANS-\d{4}-\d{6}$/;
    if (!SERIAL_RE.test(serial.trim())) {
      return c.json({
        valid: false,
        error:
          "Invalid transcript serial number format. Expected: BMI-TRANS-YYYY-NNNNNN",
        code: "INVALID_FORMAT",
      });
    }

    // ── Database lookup ────────────────────────────────────────────────────
    const pb = getPocketBase();
    const safe = (v: string) => v.replace(/["'\\]/g, "");
    const results = await pb.collection("transcripts").getList(1, 1, {
      filter: `serial_number = "${safe(serial)}"`,
    });

    if (results.totalItems === 0) {
      await logVerification(serial, "not_found", ip);
      return c.json({
        valid: false,
        error:
          "Transcript not found in the BMI University registry. " +
          "If recently issued, please try again in a few minutes.",
        code: "NOT_FOUND",
      });
    }

    const tr = results.items[0];

    // ── Revocation check ───────────────────────────────────────────────────
    if (tr.status === "REVOKED") {
      await logVerification(serial, "revoked", ip);
      return c.json({
        valid: false,
        error: "This transcript has been revoked by BMI University.",
        code: "REVOKED",
        transcript: {
          serial_number: tr.serial_number,
          student_name: tr.student_name,
          status: "revoked",
        },
      });
    }

    // ── HMAC token verification (when token is present in QR scan) ─────────
    let tokenVerified = false;
    if (token && typeof token === "string" && token.length === 24) {
      const issueDate = tr.issued_at
        ? new Date(tr.issued_at).toISOString().split("T")[0]
        : "";
      tokenVerified = verifyHiddenToken(token, {
        serial: serial.trim(),
        studentId: tr.student_id,
        issueDate,
        nonce: tr.issuance_nonce,
      });

      if (!tokenVerified) {
        await logVerification(serial, "tampered", ip);
        return c.json({
          valid: false,
          error:
            "QR token verification failed. " +
            "This transcript QR code may have been forged or tampered with. " +
            "Please contact BMI University Registrar.",
          code: "TAMPERED",
        });
      }
    }

    // ── Success: increment counter and return public fields only ───────────
    await pb.collection("transcripts").update(tr.id, {
      verification_count: (tr.verification_count || 0) + 1,
    });

    await logVerification(serial, "valid", ip);
    logger.info("Transcript verified", {
      serial,
      tokenVerified,
      verifications: (tr.verification_count || 0) + 1,
    });

    return c.json({
      valid: true,
      transcript: {
        serial_number: tr.serial_number,
        student_name: tr.student_name,
        programme: tr.programme,
        academic_year: tr.academic_year,
        issued_at: tr.issued_at,
        status: "active",
        // content_hash is intentionally NOT returned — prevents hash oracle attacks
      },
      verification: {
        timestamp: new Date().toISOString(),
        method: token ? "qr_scan" : "serial_only",
        token_verified: tokenVerified,
        /**
         * Serial-only verification (no QR token) is informational only.
         * It proves the serial exists but NOT that the physical document is genuine.
         */
        confidence: tokenVerified ? "high" : "low",
        verification_count: (tr.verification_count || 0) + 1,
      },
    });
  } catch (error: unknown) {
    logger.error("Transcript verification error:", errorMessage(error));
    return c.json(
      {
        valid: false,
        error: "Verification service temporarily unavailable. Please try again.",
        code: "SERVICE_ERROR",
      },
      500,
    );
  }
});

export default transcriptsRouter;
